-- Roshanal AI — Supabase Schema (Part 2: CRM & Leads)

-- 8. LEADS
CREATE TABLE IF NOT EXISTS leads (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  full_name TEXT NOT NULL DEFAULT '',
  email TEXT,
  phone TEXT NOT NULL,
  whatsapp TEXT,
  company TEXT,
  job_title TEXT,
  website TEXT,
  linkedin_url TEXT,
  instagram_handle TEXT,
  country TEXT NOT NULL DEFAULT 'Nigeria',
  state TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  address TEXT,
  area TEXT,
  division_interest TEXT DEFAULT 'both' CHECK (division_interest IN ('marine', 'tech', 'both')),
  product_interests TEXT[] DEFAULT '{}',
  customer_type TEXT DEFAULT 'business' CHECK (customer_type IN ('individual', 'business', 'government', 'ngo')),
  company_size TEXT CHECK (company_size IN ('micro', 'sme', 'mid', 'enterprise')),
  industry TEXT,
  stage TEXT NOT NULL DEFAULT 'new_lead',
  score NUMERIC DEFAULT 0,
  tier TEXT DEFAULT 'warm' CHECK (tier IN ('hot', 'warm', 'cold', 'disqualified')),
  icp_match NUMERIC DEFAULT 0,
  budget_signal TEXT DEFAULT 'unknown' CHECK (budget_signal IN ('high', 'medium', 'low', 'unknown')),
  urgency TEXT DEFAULT 'unknown' CHECK (urgency IN ('immediate', 'this_month', 'this_quarter', 'future', 'unknown')),
  decision_maker BOOLEAN DEFAULT false,
  qualification_status TEXT DEFAULT 'pending' CHECK (qualification_status IN ('pending', 'qualified', 'disqualified', 'manual_override')),
  qualification_grade TEXT CHECK (qualification_grade IN ('A', 'B', 'C', 'D')),
  qualification_reasons TEXT[] DEFAULT '{}',
  disqualifiers TEXT[] DEFAULT '{}',
  qualification_notes TEXT DEFAULT '',
  recommended_approach TEXT DEFAULT '',
  talking_points TEXT[] DEFAULT '{}',
  best_channel TEXT DEFAULT 'whatsapp' CHECK (best_channel IN ('whatsapp', 'email', 'call', 'sms')),
  qualified_at TIMESTAMPTZ,
  source TEXT NOT NULL DEFAULT 'manual',
  source_detail TEXT,
  utm_source TEXT,
  utm_campaign TEXT,
  tags TEXT[] DEFAULT '{}',
  notes TEXT DEFAULT '',
  emails_sent NUMERIC DEFAULT 0,
  emails_opened NUMERIC DEFAULT 0,
  emails_clicked NUMERIC DEFAULT 0,
  whatsapp_sent NUMERIC DEFAULT 0,
  sms_sent NUMERIC DEFAULT 0,
  calls_made NUMERIC DEFAULT 0,
  calls_answered NUMERIC DEFAULT 0,
  last_contacted TIMESTAMPTZ,
  last_response TIMESTAMPTZ,
  next_action TEXT DEFAULT '',
  next_action_date TIMESTAMPTZ,
  next_action_type TEXT DEFAULT 'call' CHECK (next_action_type IN ('call', 'email', 'whatsapp', 'meeting', 'demo')),
  assigned_to TEXT,
  estimated_deal_value_ngn NUMERIC,
  products_quoted TEXT[] DEFAULT '{}',
  email_consent BOOLEAN DEFAULT true,
  sms_consent BOOLEAN DEFAULT false,
  whatsapp_consent BOOLEAN DEFAULT true,
  call_consent BOOLEAN DEFAULT true,
  opted_out BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 9. CRM ACTIVITIES
CREATE TABLE IF NOT EXISTS crm_activities (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  description TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  performed_by TEXT NOT NULL DEFAULT 'system',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 10. CALL LOGS
CREATE TABLE IF NOT EXISTS call_logs (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  lead_id UUID REFERENCES leads(id) ON DELETE SET NULL,
  agent_id TEXT NOT NULL,
  call_sid TEXT NOT NULL,
  conversation_id TEXT NOT NULL,
  type TEXT CHECK (type IN ('inbound', 'outbound')),
  from_number TEXT NOT NULL,
  to_number TEXT NOT NULL,
  duration_seconds NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'initiated',
  outcome TEXT,
  transcript JSONB DEFAULT '[]',
  ai_summary TEXT DEFAULT '',
  key_points TEXT[] DEFAULT '{}',
  next_action TEXT DEFAULT '',
  audio_url TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 11. VOICE AGENTS
CREATE TABLE IF NOT EXISTS voice_agents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name TEXT NOT NULL,
  type TEXT CHECK (type IN ('inbound', 'outbound')),
  division TEXT DEFAULT 'both' CHECK (division IN ('marine', 'tech', 'both')),
  elevenlabs_agent_id TEXT,
  voice_id TEXT NOT NULL,
  system_prompt TEXT NOT NULL DEFAULT '',
  first_message TEXT NOT NULL DEFAULT '',
  is_active BOOLEAN DEFAULT true,
  total_calls NUMERIC DEFAULT 0,
  avg_duration NUMERIC DEFAULT 0,
  success_rate NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
