'use client'

import { useState, useEffect } from 'react'
import { BrainBox } from '@/components/content/brain-box'
import { TrendMatcher } from '@/components/content/trend-matcher'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Sparkles, Zap, TrendingUp, Calendar, Loader2 } from 'lucide-react'
import { motion } from 'framer-motion'

export default function ContentOverviewPage() {
  const [dailyStats, setDailyStats] = useState({
    todayIdeas: 0,
    thisWeekPosts: 0,
    autoGenerated: 0,
    scheduled: 0,
  })
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchStats = async () => {
      try {
        setLoading(true)
        const token = localStorage.getItem('accessToken')
        const res = await fetch('/api/content/ideas', {
          headers: { Authorization: `Bearer ${token}` }
        })
        const data = await res.json()
        const posts: any[] = data.ideas || data || []
        
        const today = new Date().toDateString()
        const thisWeek = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)

        setDailyStats({
          todayIdeas: posts.filter(p => new Date(p.created_at).toDateString() === today).length,
          thisWeekPosts: posts.filter(p => new Date(p.created_at) > thisWeek).length,
          autoGenerated: posts.filter(p => p.auto_generated).length,
          scheduled: posts.filter(p => p.status === 'scheduled').length,
        })
      } catch (err) {
        console.error('Error fetching stats:', err)
      } finally {
        setLoading(false)
      }
    }

    fetchStats()
  }, [])

  return (
    <div className="max-w-7xl mx-auto">
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <div className="p-2 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg">
            <Brain className="w-6 h-6 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Content Brain</h1>
            <p className="text-sm text-gray-500">AI-powered autonomous content generation</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        <div className="bg-white rounded-xl border border-gray-200 p-5">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-4 h-4 text-purple-600" />
            <span className="text-sm text-gray-600">Today's Ideas</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">
            {loading ? '...' : dailyStats.todayIdeas}
          </p>
          <p className="text-xs text-gray-500 mt-1">Auto-generated</p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-5">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp className="w-4 h-4 text-green-600" />
            <span className="text-sm text-gray-600">This Week</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">
            {loading ? '...' : dailyStats.thisWeekPosts}
          </p>
          <p className="text-xs text-gray-500 mt-1">Total content</p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-5">
          <div className="flex items-center gap-2 mb-2">
            <Calendar className="w-4 h-4 text-blue-600" />
            <span className="text-sm text-gray-600">Scheduled</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">
            {loading ? '...' : dailyStats.scheduled}
          </p>
          <p className="text-xs text-gray-500 mt-1">Ready to publish</p>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-5">
          <div className="flex items-center gap-2 mb-2">
            <Zap className="w-4 h-4 text-amber-600" />
            <span className="text-sm text-gray-600">AI Generated</span>
          </div>
          <p className="text-2xl font-bold text-gray-900">
            {loading ? '...' : dailyStats.autoGenerated}
          </p>
          <p className="text-xs text-gray-500 mt-1">No manual work</p>
        </div>
      </div>

      <BrainBox />

      <div className="mt-8 grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-gradient-to-br from-purple-50 to-blue-50 rounded-xl border border-purple-200 p-6">
          <div className="flex items-center gap-3 mb-4">
            <Zap className="w-6 h-6 text-purple-600" />
            <h3 className="font-semibold text-gray-900">Daily Automation</h3>
          </div>
          <div className="space-y-3">
            <div className="flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-purple-600 mt-2" />
              <div>
                <p className="text-sm font-medium text-gray-900">Auto-Generated Ideas</p>
                <p className="text-xs text-gray-600">10-15 ideas generated daily at 6am WAT across Marine & Tech divisions</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-blue-600 mt-2" />
              <div>
                <p className="text-sm font-medium text-gray-900">Live Trend Matching</p>
                <p className="text-xs text-gray-600">Ideas are matched to trending Nigerian topics and news</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-green-600 mt-2" />
              <div>
                <p className="text-sm font-medium text-gray-900">AI Image Generation</p>
                <p className="text-xs text-gray-600">One-click image creation using free AI (Pollinations.ai)</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-amber-600 mt-2" />
              <div>
                <p className="text-sm font-medium text-gray-900">Video Scripts</p>
                <p className="text-xs text-gray-600">UGC video scripts for testimonials, unboxing, and demos</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <div className="flex items-center gap-3 mb-4">
            <TrendingUp className="w-6 h-6 text-green-600" />
            <h3 className="font-semibold text-gray-900">Quick Actions</h3>
          </div>
          <div className="space-y-3">
            <Button
              onClick={() => window.location.href = '/dashboard/content/ideas'}
              className="w-full justify-start bg-white border border-gray-200 text-gray-900 hover:bg-gray-50"
              variant="outline"
            >
              <Sparkles className="w-4 h-4 mr-2 text-purple-600" />
              View All Ideas
            </Button>
            <Button
              onClick={() => window.location.href = '/dashboard/content/calendar'}
              className="w-full justify-start bg-white border border-gray-200 text-gray-900 hover:bg-gray-50"
              variant="outline"
            >
              <Calendar className="w-4 h-4 mr-2 text-blue-600" />
              Open Calendar
            </Button>
          </div>
        </div>
      </div>

      <div className="mt-8">
        <TrendMatcher />
      </div>
    </div>
  )
}

function Brain({ className }: { className?: string }) {
  return (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
      <path d="M12 2a7 7 0 0 1 7 7c0 2.38-1.19 4.47-3 5.74V17a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2v-2.26C6.19 13.47 5 11.38 5 9a7 7 0 0 1 7-7z" />
      <path d="M10 21h4" />
      <path d="M9 9h6" />
      <path d="M12 6v6" />
    </svg>
  )
}
