'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { BrainBox } from '@/components/content/brain-box'
import { TrendMatcher } from '@/components/content/trend-matcher'
import { PageHeader } from '@/components/dashboard/PageHeader'
import { Button } from '@/components/ui/button'
import { Brain, Sparkles, Zap, TrendingUp, Calendar, Lightbulb, CalendarDays } from 'lucide-react'

interface ContentIdea {
  id: string
  created_at: string
  auto_generated?: boolean
  status?: string
}

interface DailyStats {
  todayIdeas: number
  thisWeekPosts: number
  autoGenerated: number
  scheduled: number
}

export default function ContentOverviewPage() {
  const router = useRouter()
  const [dailyStats, setDailyStats] = useState<DailyStats>({
    todayIdeas: 0,
    thisWeekPosts: 0,
    autoGenerated: 0,
    scheduled: 0,
  })
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchStats = async () => {
      try {
        setLoading(true)
        const token = localStorage.getItem('accessToken')
        const res = await fetch('/api/content/ideas', {
          headers: { Authorization: `Bearer ${token}` }
        })
        const data = await res.json() as { ideas?: ContentIdea[] } | ContentIdea[]
        const posts: ContentIdea[] = Array.isArray(data) ? data : (data.ideas ?? [])

        const today = new Date().toDateString()
        const thisWeek = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)

        setDailyStats({
          todayIdeas: posts.filter(p => new Date(p.created_at).toDateString() === today).length,
          thisWeekPosts: posts.filter(p => new Date(p.created_at) > thisWeek).length,
          autoGenerated: posts.filter(p => p.auto_generated).length,
          scheduled: posts.filter(p => p.status === 'scheduled').length,
        })
      } catch (err) {
        console.error('Error fetching stats:', err)
      } finally {
        setLoading(false)
      }
    }

    fetchStats()
  }, [])

  return (
    <div className="max-w-full mx-auto px-4 sm:px-0">
      <PageHeader
        eyebrow="Content Brain"
        title="Marketing"
        description="Generate conversion-focused social posts for marine & technology divisions with AI."
        icon={Brain}
        actions={
          <>
            <Button
              variant="outline"
              onClick={() => router.push('/dashboard/content/ideas')}
              className="bg-white border-border-subtle text-text-primary hover:bg-bg-surface"
            >
              <Lightbulb className="w-4 h-4 mr-2 text-accent-gold" />
              View All Ideas
            </Button>
            <Button
              onClick={() => router.push('/dashboard/content/calendar')}
              className="bg-accent-primary hover:bg-accent-primary/90 text-white"
            >
              <CalendarDays className="w-4 h-4 mr-2" />
              Open Calendar
            </Button>
          </>
        }
      />

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        <div className="bg-white rounded-xl border border-border-subtle p-5">
          <div className="flex items-center gap-2 mb-2">
            <Sparkles className="w-4 h-4 text-accent-gold" />
            <span className="text-sm text-text-secondary">Today&apos;s Ideas</span>
          </div>
          <p className="text-2xl font-bold text-text-primary">
            {loading ? '...' : dailyStats.todayIdeas}
          </p>
          <p className="text-xs text-text-muted mt-1">Auto-generated</p>
        </div>
        <div className="bg-white rounded-xl border border-border-subtle p-5">
          <div className="flex items-center gap-2 mb-2">
            <TrendingUp className="w-4 h-4 text-accent-emerald" />
            <span className="text-sm text-text-secondary">This Week</span>
          </div>
          <p className="text-2xl font-bold text-text-primary">
            {loading ? '...' : dailyStats.thisWeekPosts}
          </p>
          <p className="text-xs text-text-muted mt-1">Total content</p>
        </div>
        <div className="bg-white rounded-xl border border-border-subtle p-5">
          <div className="flex items-center gap-2 mb-2">
            <Calendar className="w-4 h-4 text-accent-primary" />
            <span className="text-sm text-text-secondary">Scheduled</span>
          </div>
          <p className="text-2xl font-bold text-text-primary">
            {loading ? '...' : dailyStats.scheduled}
          </p>
          <p className="text-xs text-text-muted mt-1">Ready to publish</p>
        </div>
        <div className="bg-white rounded-xl border border-border-subtle p-5">
          <div className="flex items-center gap-2 mb-2">
            <Zap className="w-4 h-4 text-accent-gold" />
            <span className="text-sm text-text-secondary">AI Generated</span>
          </div>
          <p className="text-2xl font-bold text-text-primary">
            {loading ? '...' : dailyStats.autoGenerated}
          </p>
          <p className="text-xs text-text-muted mt-1">No manual work</p>
        </div>
      </div>

      <BrainBox />

      <div className="mt-8 grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-gradient-to-br from-accent-primary/10 to-accent-primary/5 rounded-xl border border-accent-primary/20 p-6">
          <div className="flex items-center gap-3 mb-4">
            <Zap className="w-6 h-6 text-accent-primary" />
            <h3 className="font-semibold text-text-primary">Daily Automation</h3>
          </div>
          <div className="space-y-3">
            <div className="flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-accent-primary mt-2" />
              <div>
                <p className="text-sm font-medium text-text-primary">Auto-Generated Ideas</p>
                <p className="text-xs text-text-secondary">10-15 ideas generated daily at 6am WAT across Marine &amp; Tech divisions</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-accent-primary mt-2" />
              <div>
                <p className="text-sm font-medium text-text-primary">Live Trend Matching</p>
                <p className="text-xs text-text-secondary">Ideas are matched to trending Nigerian topics and news</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-accent-emerald mt-2" />
              <div>
                <p className="text-sm font-medium text-text-primary">AI Image Generation</p>
                <p className="text-xs text-text-secondary">One-click image creation using free AI (Pollinations.ai)</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <div className="w-2 h-2 rounded-full bg-accent-gold mt-2" />
              <div>
                <p className="text-sm font-medium text-text-primary">Video Scripts</p>
                <p className="text-xs text-text-secondary">UGC video scripts for testimonials, unboxing, and demos</p>
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-border-subtle p-6">
          <div className="flex items-center gap-3 mb-4">
            <TrendingUp className="w-6 h-6 text-accent-emerald" />
            <h3 className="font-semibold text-text-primary">Quick Actions</h3>
          </div>
          <div className="space-y-3">
            <Button
              onClick={() => router.push('/dashboard/content/ideas')}
              className="w-full justify-start bg-white border border-border-subtle text-text-primary hover:bg-bg-surface"
              variant="outline"
            >
              <Sparkles className="w-4 h-4 mr-2 text-accent-gold" />
              View All Ideas
            </Button>
            <Button
              onClick={() => router.push('/dashboard/content/calendar')}
              className="w-full justify-start bg-white border border-border-subtle text-text-primary hover:bg-bg-surface"
              variant="outline"
            >
              <Calendar className="w-4 h-4 mr-2 text-accent-primary" />
              Open Calendar
            </Button>
            <Button
              onClick={() => router.push('/dashboard/social')}
              className="w-full justify-start bg-white border border-border-subtle text-text-primary hover:bg-bg-surface"
              variant="outline"
            >
              <Zap className="w-4 h-4 mr-2 text-accent-emerald" />
              Go to Social Scheduler
            </Button>
          </div>
        </div>
      </div>

      <div className="mt-8">
        <TrendMatcher />
      </div>
    </div>
  )
}
